AWSTemplateFormatVersion: 2010-09-09
Description: S3 bucket with default encryption
Resources:
  VQTLambdaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
    DeletionPolicy: Delete